#!/bin/sh

case "$1" in
    start) exec /usr/lib/systemd/systemd-udevd --daemon ;;
    stop) udevadm control -e || : ;;
    settle) exec udevadm settle ;;
    trigger) exec udevadm trigger --action=add ;;
esac

exit 1
